name: rebase

on: 
  issue_comment:
    types: [created]

jobs:
  rebase:
  
    name: rebase
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')

    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
        
    - name: rebase
      uses: cirrus-actions/rebase@1.2
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        
    - name: react
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.BOT_TOKEN }}
        comment-id: ${{ github.event.comment.id }}
        reaction-type: '+1'
